# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: 주경덕
title: Junior Developer
email: kyondoku@gmail.com
# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username: kyondoku
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: kyondoku
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
  - title: topeleven
    icon: fas fa-globe
    url: https://cosmic-douhua-fa2b23.netlify.app/
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  개발자 주경덕입니다. 새로운 것에 도전하는 자세를 가지고자 노력합니다. 백엔드 개발자로 일하고 있지만 최근에는 프론트엔드쪽에 대해서도 관심을 가지고 React를 공부하고 있습니다. 

  친구들과 스터디 그룹을 구성하여 다양한 시도를 준비하고 있습니다. 현재는 홈서버를 구축하여 구성원들의 프로젝트들을 리스트화하여 포트폴리오 역할을 하는 수준으로 활용하고 있지만, 꾸준히 발전시켜 지식을 공유하고 성장할 수 있는 플랫폼으로 만들어가고자 합니다.

  기술 스택
  - <mark>Java</mark> <mark>JavaScript</mark>
  - <mark>Spring</mark> <mark>ReactJS</mark> <mark>tailwindCSS</mark>
  - <mark>Firebase</mark> <mark>Cloudinary</mark> <mark>Netlify</mark> <mark>Postman</mark> <mark>Docker</mark>
  - <mark>OZreport</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: 한살림 차세대 마트 솔루션 구축
        sub_title: 개발
        caption: 2022.11 ~ 2023.07
        description: | # this will include new lines to allow paragraphs
          - 주문, 공급파트 화면개발
          - 전자문서 개발

          - 사용 기술
            - <mark>Java</mark> <mark>JavaScript</mark> <mark>Spring</mark> <mark>tailwindCSS</mark> <mark>OZreport</mark>

      - layout: left
        title: 중앙대학교 차세대 행정시스템 구축
        sub_title: 개발
        caption: 2022.02 ~ 2022.10
        description: | # this will include new lines to allow paragraphs
          - 산학협력단 차세대 연구행정시스템 재무, 자산, 검수 파트 화면개발
          - 전자문서 개발

          - 사용 기술
            - <mark>Java</mark> <mark>JavaScript</mark> <mark>eXBuilder6</mark> <mark>Spring</mark> <mark>OZreport</mark>

      - layout: left
        title: LG U+ 개통파트 스쿼드 참여
        sub_title: 개발
        caption: 2021.03 ~ 2022.01
        description: | # this will include new lines to allow paragraphs
          - 상시개발스쿼드 참여, 기업개통 WMS 유지보수 수행
          - 대리점, 기업개통파트간 문의응답시스템 신규화면 개발
          - 신규 개통프로세스 추가

          - 사용 기술
            - <mark>Java</mark> <mark>JavaScript</mark> <mark>websquare</mark> <mark>Spring</mark>

  - title: Side Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TOPELEVEN
        caption: 2023.09 ~
        link: https://cosmic-douhua-fa2b23.netlify.app
        description: | # this will include new lines to allow paragraphs
          ReactJS를 기반으로 온라인 쇼핑몰을 개발하고 있습니다. 인증 및 DB는 Firebase를 통해 관리하고 있고, 이미지는 파일서버 대신 Cloudinary를 통해 관리합니다.

          사용 기술
            - <mark>JavaScript</mark> <mark>ReactJS</mark> <mark>tailwindCSS</mark> <mark>Firebase</mark> <mark>Cloudinary</mark> <mark>Netlify</mark>

      - layout: left
        title: YOUTUBE Clone Coding
        caption: 2023.07 ~ 2023.08
        link: https://www.youtube.com/watch?v=vtg4o__aRMg
        description: | # this will include new lines to allow paragraphs
          Youtube API를 활용한 Youtube Clone Coding 프로젝트 입니다. 로그인에 대한 인증은 Firebase를 활용하였습니다.

          사용 기술
            - <mark>JavaScript</mark> <mark>ReactJS</mark> <mark>Firebase</mark> <mark>Netlify</mark>

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
